os: linux
language: minimal
services:
  - docker

jobs:
  include:
    - name: "checks"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t rusdevops/bootstrap-cpp scripts/checks.sh
    - name: "tests"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/tests.sh

notifications:
  email: false

branches:
  except:
    - master
    
    
